name: CMake

on:
  push:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Release]

    steps:
    - uses: actions/checkout@v3

    - name: Environment setup
      run: sudo tools/installers/essentials.sh

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build/masscalculator-docker-${{matrix.build_type}} -G Ninja -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Docker Build - masscalculator-cli
      run: cmake --build ${{github.workspace}}/build/masscalculator-docker-${{matrix.build_type}} -t build-masscalculator-cli-docker --config ${{matrix.build_type}}

    - name: Docker Build - masscalculator-core
      run: cmake --build ${{github.workspace}}/build/masscalculator-docker-${{matrix.build_type}} -t build-masscalculator-core-docker --config ${{matrix.build_type}}

    - name: Docker Build - masscalculator-gui
      run: cmake --build ${{github.workspace}}/build/masscalculator-docker-${{matrix.build_type}} -t build-masscalculator-gui-docker --config ${{matrix.build_type}}

    - name: Docker Build - masscalculator-yocto
      run: cmake --build ${{github.workspace}}/build/masscalculator-docker-${{matrix.build_type}} -t build-masscalculator-yocto-docker --config ${{matrix.build_type}}

    - name: Docker Run - masscalculator-cli
      run: cmake --build ${{github.workspace}}/build/masscalculator-docker-${{matrix.build_type}} -t run-masscalculator-cli-docker --config ${{matrix.build_type}}

    - name: Docker Run - masscalculator-core
      run: cmake --build ${{github.workspace}}/build/masscalculator-docker-${{matrix.build_type}} -t run-masscalculator-core-docker --config ${{matrix.build_type}}

    - name: Docker Run - masscalculator-gui
      run: cmake --build ${{github.workspace}}/build/masscalculator-docker-${{matrix.build_type}} -t run-masscalculator-gui-docker --config ${{matrix.build_type}}

    - name: Docker Run - masscalculator-yocto
      run: cmake --build ${{github.workspace}}/build/masscalculator-docker-${{matrix.build_type}} -t run-masscalculator-yocto-docker --config ${{matrix.build_type}}

    - name: Deploy
      run: echo 'Deploy stage is in progress'

  trigger:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.merged == true

    steps:
      - name: Send repository dispatch event
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: MassCalculator/masscalculator.github.io
          event-type: masscalculator-docker-pr-merged
          token: ${{secrets.MASSCALCULATOR_SECRET}}
